# Generated by Django 4.1.6 on 2023-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_description_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(related_name='reviews', to='home.product'),
        ),
    ]
