# Generated by Django 4.1.6 on 2023-03-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230219_0024'),
        ('home', '0013_remove_review_product_review_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='products',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=9.995002498750625e-06, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
