# Generated by Django 4.1.6 on 2023-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230219_0024'),
        ('home', '0015_remove_review_product_review_products_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='products',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='products.product'),
        ),
    ]
