# Generated by Django 4.1.6 on 2023-03-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='name1',
        ),
    ]
