# Generated by Django 4.1.6 on 2023-03-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_email_subscriber_email1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='name1',
            new_name='name',
        ),
    ]
