# Generated by Django 3.2 on 2023-02-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
